name: Validate Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checking project out
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restoring cache prior to install
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Installing Deps
        run: yarn install

      - name: Linting Project
        run: yarn lintfix

      - name: Building Project
        run: yarn build
